input {
  beats {
    port => 5044
  }

  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "pipeline" => "logstash"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://es-hot:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
